export function getScaffoldAppLayoutTsx() {
  return `import React from "react";
import { BuiltWithBadge } from "@/components/built-with-badge";

export const metadata = {
  title: "Generated SaaS Template",
  description: "Generated by SaaS Builder",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        {children}
        <BuiltWithBadge />
      </body>
    </html>
  );
}
`;
}
