/**
 * Setup Guide Template Generator
 *
 * Generates a Japanese setup guide to include in ZIP exports.
 */

const TEMPLATE_LABELS: Record<string, string> = {
  membership_content_affiliate: "会員コンテンツ配信 + アフィリエイト SaaS",
  reservation_saas: "予約管理 SaaS",
  simple_crm_saas: "シンプル CRM SaaS",
  community_membership_saas: "コミュニティ会員制 SaaS",
  internal_admin_ops_saas: "社内管理オペレーション SaaS",
};

export function generateSetupGuide(
  projectName: string,
  templateKey: string,
): string {
  const templateLabel = TEMPLATE_LABELS[templateKey] ?? templateKey;

  return `# ${projectName} — セットアップガイド

> テンプレート: ${templateLabel}
> 生成日: ${new Date().toISOString().split("T")[0]}
> Generated by AI SaaS Builder

---

## 前提条件

- **Node.js** 18.x 以上
- **npm** 9.x 以上
- **Git**（推奨）

## 1. Supabase プロジェクトの作成

1. [Supabase](https://supabase.com) にアクセスし、アカウント作成
2. 「New Project」からプロジェクトを作成
3. ダッシュボードの **Settings > API** から以下をコピー:
   - \`Project URL\` → \`.env.local\` の \`NEXT_PUBLIC_SUPABASE_URL\`
   - \`anon public\` key → \`.env.local\` の \`NEXT_PUBLIC_SUPABASE_ANON_KEY\`
   - \`service_role\` key → \`.env.local\` の \`SUPABASE_SERVICE_ROLE_KEY\`

## 2. 環境変数の設定

\`\`\`bash
cp .env.example .env.local
\`\`\`

\`.env.local\` を開き、各変数を設定してください。

## 3. データベースのセットアップ

Supabase ダッシュボードの SQL Editor で、\`supabase/\` フォルダ内のマイグレーションファイルを順番に実行してください。

## 4. アプリケーションの起動

\`\`\`bash
npm install
npm run dev
\`\`\`

ブラウザで [http://localhost:3000](http://localhost:3000) を開きます。

## 5. Stripe の設定（任意）

サブスクリプション決済を有効にする場合:

1. [Stripe](https://stripe.com) にアカウント作成
2. ダッシュボードから API キーを取得:
   - \`Publishable key\` → \`NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY\`
   - \`Secret key\` → \`STRIPE_SECRET_KEY\`
3. Webhook エンドポイントを設定:
   - URL: \`https://your-domain.com/api/webhooks/stripe\`
   - イベント: \`checkout.session.completed\`, \`customer.subscription.updated\`, \`customer.subscription.deleted\`
   - Webhook Secret → \`STRIPE_WEBHOOK_SECRET\`

## よくあるエラーと対処法

| エラー | 原因 | 対処法 |
|--------|------|--------|
| \`NEXT_PUBLIC_SUPABASE_URL is missing\` | 環境変数が未設定 | \`.env.local\` を確認 |
| \`relation "xxx" does not exist\` | マイグレーション未実行 | SQL Editor でマイグレーションを実行 |
| \`Invalid API key\` | Supabase キーの間違い | ダッシュボードから再コピー |
| \`Module not found\` | 依存関係の未インストール | \`npm install\` を再実行 |

## サポート

- GitHub Issues: バグ報告・機能要望
- Discord: コミュニティサポート

---

*このプロジェクトは AI SaaS Builder によって生成されました。*
`;
}

export function generateEnvExample(templateKey: string): string {
  const base = `# Supabase
NEXT_PUBLIC_SUPABASE_URL=https://your-project.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=your-anon-key
SUPABASE_SERVICE_ROLE_KEY=your-service-role-key

# Stripe (任意)
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_xxx
STRIPE_SECRET_KEY=sk_test_xxx
STRIPE_WEBHOOK_SECRET=whsec_xxx
`;

  return base;
}
