-- Enable RLS on all tables (V7_002 - 2026-04-06)
-- Generated by M5 auto-executor
--
-- NOTE: Table-specific policies are defined in:
--   - 0012_enable_rls.sql  (tenants, users, tenant_users, projects, blueprints,
--                           generated_modules, billing_products, billing_prices,
--                           subscriptions, affiliates, referrals, commissions,
--                           audit_logs, notifications, contents, membership_plans,
--                           implementation_runs, generated_files, generation_runs,
--                           quality_runs, baseline_promotions)
--   - 0013_stripe_webhook_events.sql (stripe_webhook_events — service_role only)
--   - 20260406000001_enable_rls_all_tables.sql (hardened helper + idempotent re-verify)
--
-- This migration provides a safety-net DO block that enables RLS on any
-- public table not covered by the above migrations (e.g. tables added by
-- future migrations that forget to call ENABLE ROW LEVEL SECURITY).

-- Enable RLS on each table that currently lacks it
DO $$
DECLARE
  tbl TEXT;
BEGIN
  FOR tbl IN
    SELECT tablename FROM pg_tables
    WHERE schemaname = 'public'
      AND tablename NOT IN ('schema_migrations', '_prisma_migrations')
  LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);
  END LOOP;
END $$;

-- ============================================================
-- Tenant-scoped tables (tenant_id column)
-- Policy: only members of the tenant may access rows.
-- ============================================================

-- tenants
ALTER TABLE IF EXISTS public.tenants ENABLE ROW LEVEL SECURITY;
CREATE POLICY IF NOT EXISTS "tenant_select" ON public.tenants
  FOR SELECT USING (public.user_belongs_to_tenant(id));
CREATE POLICY IF NOT EXISTS "tenant_update" ON public.tenants
  FOR UPDATE USING (owner_user_id = auth.uid());

-- tenant_users
ALTER TABLE IF EXISTS public.tenant_users ENABLE ROW LEVEL SECURITY;
CREATE POLICY IF NOT EXISTS "tenant_users_select" ON public.tenant_users
  FOR SELECT USING (public.user_belongs_to_tenant(tenant_id));
CREATE POLICY IF NOT EXISTS "tenant_users_insert" ON public.tenant_users
  FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY IF NOT EXISTS "tenant_users_update" ON public.tenant_users
  FOR UPDATE USING (user_id = auth.uid());

-- projects
ALTER TABLE IF EXISTS public.projects ENABLE ROW LEVEL SECURITY;
CREATE POLICY IF NOT EXISTS "projects_all" ON public.projects
  FOR ALL USING (public.user_belongs_to_tenant(tenant_id));

-- subscriptions
ALTER TABLE IF EXISTS public.subscriptions ENABLE ROW LEVEL SECURITY;
CREATE POLICY IF NOT EXISTS "subscriptions_select_own" ON public.subscriptions
  FOR SELECT USING (user_id = auth.uid() OR public.user_belongs_to_tenant(tenant_id));

-- audit_logs (read-only for tenant members; writes via service_role only)
ALTER TABLE IF EXISTS public.audit_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY IF NOT EXISTS "audit_logs_select" ON public.audit_logs
  FOR SELECT USING (public.user_belongs_to_tenant(tenant_id));

-- ============================================================
-- User-owned tables (user_id column)
-- ============================================================

-- users
ALTER TABLE IF EXISTS public.users ENABLE ROW LEVEL SECURITY;
CREATE POLICY IF NOT EXISTS "users_select_own" ON public.users
  FOR SELECT USING (id = auth.uid());
CREATE POLICY IF NOT EXISTS "users_update_own" ON public.users
  FOR UPDATE USING (id = auth.uid());

-- ============================================================
-- Service-role only tables (no authenticated user access)
-- ============================================================

-- stripe_webhook_events
ALTER TABLE IF EXISTS public.stripe_webhook_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY IF NOT EXISTS "stripe_webhook_events_deny_all" ON public.stripe_webhook_events
  AS RESTRICTIVE FOR ALL USING (false) WITH CHECK (false);
