import { ProjectFormValues } from "@/types/project";

export const communityMembershipSaasPreset: Partial<ProjectFormValues> = {
  templateKey: "community_membership_saas",
  brandTone: "modern",
  requiredFeatures: [
    "member_management",
    "content_management",
    "subscription_billing",
    "one_time_purchase",
    "tag_based_access",
    "admin_dashboard",
  ],
  managedData: [
    "tenants",
    "memberships",
    "contents",
    "membership_plans",
    "subscriptions",
    "purchases",
    "tags",
    "user_tags",
    "content_access_rules",
    "audit_logs",
  ],
  endUserCreatedData: ["profile"],
  roles: ["owner", "admin", "member"],
  billingModel: "hybrid",
  affiliateEnabled: false,
  visibilityRule: "public | members_only | rules_based",
  mvpScope: [
    "auth",
    "tenant",
    "roles",
    "content_crud",
    "content_access_control",
    "subscription_billing",
    "one_time_purchase",
    "tag_management",
    "audit_log",
  ],
  excludedInitialScope: [
    "invite_token_flow",
    "membership_update_delete",
    "last_owner_protection",
    "self_downgrade",
    "advanced_analytics",
    "mobile_app",
    "multi_language",
    "drip_content",
    "scheduled_release",
  ],
  stackPreference: "Next.js + Supabase + Stripe",
  priority: "high",
};
